### ISSUE TITLE
How exactly are file arguments passed to the executables?

### ISSUE THREAD

**Issue by GeigerJ2** [C2SM/ETHIOPIA#8]
Consider the attached simplified workflow, in which the `init` *cycle* and only one `ICON` are being executed:
How are the actual file references passed around? For instance, in the call to the `ICON` executable, how are the locations of "icon input" and "grid file" passed to `ICON`? As positional parameters or via option flags (`--grid-file <path_to_gridfile>`). For further development of the AiiDA-powered runner, it would be very beneficial for us, if we could see how one would run the workflow without any workflow manager, by calling the executables / scripts manually, modifying file locations, etc.

Pinging @agoscinski and @leclairm.

![image](https://github.com/C2SM/WCFlow/assets/41700727/c40f22ba-b7dc-4977-b6b9-a7d5fca3b42e)

**Comment by agoscinski** [comment]
In a meeting we clarified that the namelist is assumed to be in the same directory with a certain name. The aiida-icon plugin will take care of it ([see calcjob input port](https://github.com/aiida-icon/aiida-icon/blob/a982d8792006bf234fe79c18aa76fd2af7a3463f/src/aiida_icon/calculations.py#L27)). In our part of the code one has to only specify the name through our plugin interface (which we still need to decide how to do, here is the draft PR #20, but this is outside of the issue)
