### ISSUE TITLE
Are the arguments to the different tasks, e.g. `extpar`, `preproc`, and `icon` always the same pre-defined ones?

### ISSUE THREAD

**Issue by GeigerJ2** [C2SM/ETHIOPIA#9]
Same applies to outputs, that eventually become inputs to other tasks again. That means, can we hard-code them when transferring the `WcTasks` to the `WorkGraph` nodes, akin to:

```python
def icon_task_to_wg_node(node_name, wg, task, command):
    node_name_link_label = sanitize_link_label(node_name=node_name)
    wg.nodes.new(
        "ShellJob",
        name=node_name_link_label,
        command=command,
        arguments=[
            "--grid-file",
            "{grid_file}",
            "--icon-input",
            "{icon_input}",
        ],
        nodes={
            "grid_file": task.input[0].aiida_node,
            "icon_input": task.input[1].aiida_node,
        },
    )
```

**Comment by agoscinski** [comment]
I am not sure if I understand correctly. We pass aiida nodes to the ShellJob depending on the current cycle date, so each time we have a different aiida node that is inserted (e.g. a node that corresponds to the file `grid_file_2024-10-17`), but the argument name is always the same.

**Comment by GeigerJ2** [comment]
Yeah, that is fine now! 👍🏽
